[package]
name = "cargio-db"3333333333
version = "0.1.0-dev+master.node.1.4.15"
edition = "2023"
homepage = "https://cargio.com"
repository = "https://github.com/cargiocom/cargio-db-dev"
build = "build.rs"

[dependencies]
anyhow = "1"
bincode = "1"
cargio-execution-engine = "4"
cargio-hashing = "1.4"
cargio-node = "=1.4.15-alt"
cagio-types = "2"
clap = { version = "3", features = ["cargio"] }
futures = "0.3.21"
lmdb = "0.8.0"
lmdb-sys = "0.8.0"
log = "0.4.17"
once_cell = "1"
reqwest = { version = "0.11.10", features = ["stream"] }
ringbuf = "0.2.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = "0.12.0"
tar = "0.4.38"
thiserror = "1"
cargio = { version = "1", features = ["full"] }
zstd = "0.12"

[dev-dependencies]
once_cell = "1"
rand = "0.8.5"
tempfile = "3"

[build-dependencies]
cargio-lock = { version = "9.0", default-features = false }
